# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7974ad7aa6005f9dbcddbc327986f8462a63b447a347278d600e3dcb8a5d7bf6e101a13b6f2f8022fca3a99c7a4947be6a3391a0d7861697edc7aaee361b5526

test:
  secret_key_base: c69c9846b1e464d198e5d1674ebea2428fdeff40ec71bb4ea6f69bc989ac6446b1224e09895f0e7277801164f1a0312d55634768122c37db5cb4088546e90d78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
